spring.application.name=internshiprecommendation

# --- MySQL Database Config ---
spring.datasource.url=jdbc:mysql://localhost:3306/internshipdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Jhanani@8507

# Auto-creates tables from @Entity classes on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Runs data.sql after tables are created
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# --- Gemini API Key ---
gemini.api.key=
spring.mvc.pathmatch.use-suffix-pattern=false
spring.web.resources.add-mappings=false

# --- Development Template Encoding ---
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB